name=Arduino_Modulino
version=0.9.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Arduino Library for Modulinos
paragraph=Easily connect and control your hardware with the Arduino Modulino® Library. Designed for the plug-and-play Qwiic ecosystem, this library makes it simple to manage sensors and actuators over I2C.
category=Communication
url=https://github.com/arduino-libraries/Arduino_Modulino
architectures=*
includes=Arduino_Modulino.h
depends=STM32duino VL53L4CD,STM32duino VL53L4ED,Arduino_LSM6DSOX,Arduino_LPS22HB,Arduino_HS300x,ArduinoGraphics,Arduino_LTR381RGB
