using System.Text;

namespace SmoothFontCreator;

public class VLWGlyph
{
   public Int32 uChar;
   public Int32 Height;
   public Int32 Width;
   public Int32 gxAdvance;
   public Int32 gdY;
   public Int32 gdX;
   public Int32 padding = 0;
   public Bitmap Bitmap;
   public VLWFont Font { get; }

   public UInt32 Ascent => Font.Ascent;
   public Int32 Descent => Font.Descent;
   public UInt32 CellWidth => (UInt32) gxAdvance;
   public UInt32 CellHeight => Font.Height;

   public VLWGlyph(VLWFont font)
   {
      this.Font = font;
   }
}

public class VLWFont
{
   public UInt32 Version { get; internal set; } = 11;
   public UInt32 FontSizePx { get; internal set; }
   public UInt32 Ascent { get; internal set; }
   public Int32 Descent { get; internal set; } // sometimes the descent is saved as a negative value

   public UInt32 Height => (UInt32)(Ascent + Math.Abs(Descent));

   public String FontName { get; internal set; } = "";
   public String PostscriptName { get; internal set; } = "";
   public bool AntiAliased { get; internal set; } = true;

   public Dictionary<Int32, VLWGlyph> Glyphs = [];

   public int NumChars => Glyphs.Count;

   private void _load(byte[] data)
   {
      ByteReader reader = new(data);
      uint gCount = reader.UInt32();
      Version = reader.UInt32();
      FontSizePx = reader.UInt32();
      reader.UInt32(); // deprecated mboxY value
      Ascent = reader.UInt32();
      Descent = reader.Int32();

      for (int i = 0; i < gCount; i++)
      {
         VLWGlyph g = new(this);
         g.uChar = reader.Int32();
         g.Height = reader.Int32();
         g.Width = reader.Int32();
         g.gxAdvance = reader.Int32();
         g.gdY = reader.Int32();
         g.gdX = reader.Int32();
         g.padding = reader.Int32();
         Glyphs.Add(g.uChar, g);
      }

      foreach (VLWGlyph g in Glyphs.Values)
      {
         if (g.Width > 0 && g.Height > 0)
         {
            g.Bitmap = reader.Bitmap(g.Width, g.Height);
         }
         else
         {
            g.Bitmap = new Bitmap(1, 1);
         }
      }

      if (reader.RemainingBytes > 0)
      {
         byte nameLength = reader.Byte();
         for (int i = 0; i < nameLength; i++)
         {
            FontName += (char)reader.Byte();
         }
         reader.Byte(); // \0 string termination

         byte postscriptNameLength = reader.Byte();
         for (int i = 0; i < postscriptNameLength; i++)
         {
            PostscriptName += (char)reader.Byte();
         }
         reader.Byte(); // \0 string termination

         AntiAliased = reader.Byte() > 0;
      }
   }

   public VLWFont()
   {

   }

   public VLWFont(byte[] data)
   {
      _load(data);
   }

   public VLWFont(string vlwFile)
   {
      _load(File.ReadAllBytes(vlwFile));
   }

   public byte[] ToByteArray()
   {
      ByteWriter writer = new();

      writer.Add(Glyphs.Count);
      writer.Add(Version);
      writer.Add(FontSizePx);
      writer.Add(0); // deprecated mboxY value
      writer.Add(Ascent);
      writer.Add(Descent);

      foreach (VLWGlyph g in Glyphs.Values)
      {
         writer.Add(g.uChar);
         writer.Add(g.Height);
         writer.Add(g.Width);
         writer.Add(g.gxAdvance);
         writer.Add(g.gdY);
         writer.Add(g.gdX);
         writer.Add(g.padding);
      }

      foreach (VLWGlyph g in Glyphs.Values)
      {
         if (g.Bitmap != null)
         {
            writer.Add(g.Bitmap);
         }
      }

      return writer.GetBytes();
   }

   public void SaveAsVLW()
   {

   }

   public void SaveAsSmoothFont(string folderPath, string name, string notes)
   {
      StringBuilder sb = new();

      sb.Append("#pragma once\n");
      sb.Append('\n');
      sb.Append("//\n");

      sb.Append($"// VLW Font Generated by Smooth Fonts Generator on {DateTime.Now.ToString("MM/dd/yyyy")}\n");
      sb.Append("//\n");

      string[] lines = notes.Split('\n', StringSplitOptions.RemoveEmptyEntries);
      foreach (string line in lines)
      {
         sb.Append("//   " + line + "\n");
      }

      sb.Append("//\n");
      sb.Append('\n');
      sb.Append($"const uint8_t {name}[] PROGMEM = {{\n");

      byte[] data = ToByteArray();
      for (int i = 0; i < data.Length; i++)
      {
         sb.Append(data[i].ToHex());
         sb.Append(", ");

         if ((i + 1) % 16 == 0)
         {
            sb.Append('\n');
         }
      }

      sb.Append('\n');
      sb.Append("};");

      string filePath = folderPath + Path.DirectorySeparatorChar + name + ".h";
      File.WriteAllText(filePath, sb.ToString());
   }
}
